[project]
name = "aranyani"
version = "0.1.0"
description = "Protecting Lives, Preserving the wild"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "inference>=0.63.2",
    "supervision>=0.27.0",
    "tensorflow-cpu>=2.20.0",
    "ultralytics>=8.3.246",
]
